name = "IncubatorRegistry"
uuid = "9ffb1216-397f-4625-8233-7f2dc4eaff38"
repo = "git@github.com:KyleSJohnston/IncubatorRegistry.git"
description = "Packages under development"

[packages]
853cdae6-d31d-485b-952e-6d292502e0c8 = { name = "OpenFIGI", path = "O/OpenFIGI" }
